global VARS_GLOBAL_ANIM
if (isempty(who('VARS_GLOBAL_ANIM'))||isempty(VARS_GLOBAL_ANIM))
    VARS_GLOBAL_ANIM = emptyVarsGlobalAnimStruct;
end
VARS_GLOBAL_ANIM.video_compression = 'PNG1';

concatVideosSmooth_temporal(...
    {...
        'render/video_4cartwheels.avi',...
        'render/video_feature_matrices_noweights.avi',...
        'render/video_feature_matrices_weights.avi',...
        'render/video_feature_matrices_reference_highlighted.avi',...
        'render/video_feature_matrices_warped.avi',...
        'render/video_feature_matrices_warped_averaging1.avi',...
        'render/video_feature_matrices_warped_averaging2.avi',...
        'render/video_feature_matrices_warped_averaging3.avi',...
        'render/video_motion_templates_iteration1_1.avi',...
        'render/video_motion_templates_iteration1_2.avi',...
        'render/video_motion_templates_iteration1_3.avi',...
        'render/video_motion_templates_iteration1_4.avi',...
        'render/video_templates_iterations.avi',...
        'render/video_class_template_cartwheel_padded.avi',...
        'render/video_class_template_cartwheel_discussion_concat.avi',...
    },...
    'render/03_WMTs.avi',...
    {...
        [],...
        [],...        
        [],...        
        [],...        
        [],...        
        [],...        
        [],...        
        [],...        
        [],...        
        [],...        
        [],...        
        [],...        
        'render/emptyGray640x480.tif',...        
        [],...        
        [],...        
    },...
    [...
        NaN,...
        0.25,...
        0.25,...
        0.25,...
        0.25,...
        0.25,...
        0.25,...
        0.25,...
        0.25,...
        0.25,...
        0.25,...
        0.25,...
        0.0,...
        0.25,...
        0.25,...
    ],...
    [...
        15 60;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 30;...
        0 0;...
        0 30;...
    ]...
    );

%'render/emptyGray640x480.tif',...        