global VARS_GLOBAL
global VARS_GLOBAL_ANIM
if (isempty(who('VARS_GLOBAL_ANIM'))||isempty(VARS_GLOBAL_ANIM))
    VARS_GLOBAL_ANIM = emptyVarsGlobalAnimStruct;
end
VARS_GLOBAL_ANIM.video_compression = 'PNG1';
VARS_GLOBAL_ANIM.figure_position = [5 100 640 240];

close all hidden;
 
downsampling_fac = 4;
sampling_rate_string = num2str(120/downsampling_fac);
feature_set_array = {'AK_upper','AK_lower','AK_mix'};
features_select = [3 4 5 6 15 16 29 30 33 34];

render_video = [0 0 0 0 0 0 1];
%render_video = [0 1 1 1 1 1 1];
concat = true;

times = [12 60/30 100/30 120/30 100/30 100/30 147/30];

myfig = figure('position',[30 100 640 240],'color',[192 192 192]/255);
left = 0.025 ;
bottom = 0.075;
width = 0.95;
height = 0.9;

load motionTemplates_4cartwheels_iteration32_b
axes_U = axes('position',[left bottom width height]);
imagesc(U_out{1}(features_select,:),[0 1]); colormap hot;
UCbar = colorbar; set(UCbar,'fontsize',8); set(UCbar,'position',get(UCbar,'position')-[0.01 0 0 0]); 
set(gca,'ytick',[]);
set(gca,'fontsize',8);
if (render_video(1))
    grabVideoFrames(myfig,times(1)*30,['render/video_class_template_cartwheel.avi']);
end

if (render_video(2))
    grabVideoFrames(myfig,times(2)*30,['render/video_class_template_cartwheel_discussion1.avi']);
end

boxes(1) = drawBox(myfig,[0.24 0.675 0.13 0.15],[0 150 255]/255);
if (render_video(3))
    grabVideoFrames(myfig,times(3)*30,['render/video_class_template_cartwheel_discussion2.avi']);
end

boxes(2) = drawBox(myfig,[0.28 0.496 0.16 0.15],[0 150 255]/255);
if (render_video(4))
    grabVideoFrames(myfig,times(4)*30,['render/video_class_template_cartwheel_discussion3.avi']);
end
delete(boxes(1));
delete(boxes(2));

boxes(3) = drawBox(myfig,[0.385 0.77 0.27 0.23],[0 150 255]/255);
if (render_video(5))
    grabVideoFrames(myfig,times(5)*30,['render/video_class_template_cartwheel_discussion4.avi']);
end

boxes(4) = drawBox(myfig,[0.415 0.048 0.19 0.23],[0 150 255]/255);
if (render_video(6))
    grabVideoFrames(myfig,times(6)*30,['render/video_class_template_cartwheel_discussion5.avi']);
end
delete(boxes(3));
delete(boxes(4));

boxes(5) = drawBox(myfig,[0.74 0.048 0.108 0.95],[0 150 255]/255);
if (render_video(7))
    grabVideoFrames(myfig,times(7)*30,['render/video_class_template_cartwheel_discussion6.avi']);
end

% padVideo('render/video_class_template_cartwheel.avi','render/video_class_template_cartwheel_padded.avi',[192 192 192],240,'t');

if (concat)
    concatVideosSmooth_temporal(...
    {...
        'render/video_class_template_cartwheel_discussion1.avi',...
        'render/video_class_template_cartwheel_discussion2.avi',...
        'render/video_class_template_cartwheel_discussion3.avi',...
        'render/video_class_template_cartwheel_discussion4.avi',...
        'render/video_class_template_cartwheel_discussion5.avi', ...
        'render/video_class_template_cartwheel_discussion6.avi' ...
    },...
    'render/video_class_template_cartwheel_discussion.avi',...
    {...
        [],...
        [],...        
        [],...        
        [],...        
        [], ...        
        [] ...        
    },...
    [...
        NaN,...
        0.25,...
        0.25,...
        0.25,...
        0.25, ...
        0.25 ...
    ],...
    [...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0;...
        0 0 ...
    ]...
    );
end