function info = forAllFiles_filename2info_HDM_training(startdir)
% info=forallfiles_filename2info_hdm_training('S:\data_MoCap\MoCaDaDB\HDM\Training')
info = struct('amcname','',...
              'asfname','',...
              'amcpath','',...
              'filetype','ASF/AMC',...
              'skeletonSource','',...
              'skeletonID','',...
              'motionCategory','',...
              'motionDescription','',...
              'motionClass','',...
              'numReps','',...
              'samplingRate',0);
info = repmat(info,0,0);          
info = forAllFilesInDir(startdir, {'*.amc'}, @filename2info_HDM_training, true, info);