function scatter_win_select_variables(ud)

% SCATTER_WIN_SELECT_VARIABLES opens a window for selecting variables (scatter).
% --------------------------------
% scatter_win_select_variables(ud)
% --------------------------------
% Description: opens a window for selecting variables (scatter).
% Input:       {ud} userdata of parent window.

% © Liran Carmel
% Classification: Visualization
% Last revision date: 18-Jan-2005

% extract relevant parameters from {ud}
lt = ud.data;
vars = ud.variables;

% open window
name = sprintf('Select Factors (total %d)',lt.no_factors);
fig = figure('menubar','none','position',[300 300 500 400],...
    'numbertitle','off','name',name);

% define editable text
uicontrol(fig,'style','text','horizontal','left',...
    'units','normalized','position',[0.05 0.88 0.23 0.05],...
    'string','Factor for x-axis:','background',[0.8 0.8 0.8]);
h_ed(1) = uicontrol(fig,'style','edit',...
    'units','normalized','position',[0.28 0.88 0.05 0.05],...
    'background',[0.8 0.8 0.8],'horizontal','left',...
    'callback','loadings(lintrans,101)');
uicontrol(fig,'style','text','horizontal','left',...
    'units','normalized','position',[0.55 0.88 0.23 0.05],...
    'string','Factor for y-axis:','background',[0.8 0.8 0.8]);
h_ed(2) = uicontrol(fig,'style','edit',...
    'units','normalized','position',[0.78 0.88 0.05 0.05],...
    'background',[0.8 0.8 0.8],'horizontal','left',...
    'callback','loadings(lintrans,102)');

% define listbox
name_factors = samplenames(lt.factorset);
scores = lt.scores;
h_lb(1) = uicontrol(fig,'style','listbox',...
    'string',name_factors,...
    'units','normalized','position',[0.05 0.12 0.4 0.75],...
    'callback','loadings(lintrans,103)');
h_lb(2) = uicontrol(fig,'style','listbox',...
    'string',name_factors,...
    'units','normalized','position',[0.55 0.12 0.4 0.75],...
    'callback','loadings(lintrans,104)');

% define OK and Cancel buttons
uicontrol(fig,'style','push','string','O.K.',...
    'units','normalized','position',[0.125 0.03 0.3 0.06],...
    'callback','loadings(lintrans,105)');
uicontrol(fig,'style','push','string','Cancel',...
    'units','normalized','position',[0.575 0.03 0.3 0.06],...
    'callback','close(gcf)');

% initialize window to previos selection
set(h_lb(1),'value',vars(1));
set(h_ed(1),'string',num2str(vars(1)));
set(h_lb(2),'value',vars(2));
set(h_ed(2),'string',num2str(vars(2)));
 
% define userdata
ud = struct('data',lt,'variables',vars,'h_ed',h_ed,'h_lb',h_lb,...
    'main_fig',ud.main_fig);
set(gcf,'userdata',ud);