function features_spec = features_spec_struct(features_num)

features_spec_single = struct('name','',...
                              'win_offset_rel',0.5,...
                              'win_length_ms',100,...
                              'params',[]);                   
                   
features_spec = repmat(features_spec_single,features_num,1);