function classDefinition = createClassDefinition()
classDefinition = struct();

classDefinition.neutral = {'standStill2000'};

classDefinition.tpose = {'tpose1000'};

classDefinition.move = {      'shuffle2StepsLStart', ...
                              'sneak2StepsLStart', ...
                              'staircaseDown2Lstart',...
                              'staircaseUp2Lstart',...
                              'walk2StepsLstart',...
                              'walkBackwards2StepsLstart',...
                              'walkLeftCircle2StepsLstart',...
                              'walkRightCircle2StepsLstart',...
                              'jog2StepsLstart',...
                              'jog2StepsLstartMirrored', ...
                              'jogLeftCircle2StepsLstart'...
                              'jogLeftCircle2StepsRstart',...
                              'jogRightCircle2StepsLstart',...
                              'jogRightCircle2StepsRstart',...
                              'shuffle2StepsRStart', ...
                              'sneak2StepsRStart', ...
                              'staircaseDown2Rstart',...
                              'staircaseUp2Rstart',...
                              'walk2StepsRstart',...
                              'walkBackwards2StepsRstart',...
                              'walkLeftCircle2StepsRstart',...
                              'walkRightCircle2StepsRstart',... %Additional classes that previously belonged to 'others'
                              'walkRightCrossFront2Steps',...  
                              'walkRightCrossFront2StepsMirrored',...
                              'walkLeft2Steps',...
                              'walkLeft2StepsMirrored',...                              
                              };
                          
 classDefinition.turn = {...
                        'turnLeft',...
                        'turnRight',...
                        };  
                    
classDefinition.sitLieDown = {'lieDownFloorNew', ...
                       'sitDownChairNew',...
                       'sitDownFloorNew',...
                       'sitDownKneelTieShoesNew',...
                       };
                   
classDefinition.standUp = {'standUpKneelToStandNew',...        
                           'standUpLieFloorNew',...
                           'standUpSitChairNew',...
                           'standUpSitFloorNew',...
                           };
                       
classDefinition.hopOneLeg ={'hopLLeg1hops',...
                          'hopRLeg1hops',...
                          };
                      
classDefinition.jump =   {'hopBothLegs1hops',...
                          'jumpDown',...
                          'jumpingJack1Reps',...
                          };
                      
classDefinition.kick = {'kickLFront1Reps',...
                        'kickLSide1Reps', ...
                        'kickRFront1Reps',...
                        'kickRSide1Reps', };
                    
classDefinition.punch = {'punchLFront1Reps', 'punchLSide1Reps',...
                         'punchRFront1Reps', 'punchRSide1Reps'};
                     
classDefinition.rotateArms = {'rotateArmsBothBackward1Reps', ...
                              'rotateArmsBothForward1Reps',...
                              'rotateArmsLBackward1Reps',...
                              'rotateArmsLForward1Reps',...
                              'rotateArmsRBackward1Reps',...
                              'rotateArmsRForward1Reps',...
                              };
                          
classDefinition.throwR =  {'throwSittingHighR', ...
                          'throwSittingLowR',...
                          'throwStandingHighR',...
                          'throwStandingLowR',...
                          };
                      
classDefinition.grabDepR = {'depositHighR', 'depositLowR', 'depositMiddleR', 'grabHighR', 'grabLowR', 'grabMiddleR',...
                                'depositFloorR', 'grabFloorR'};
                            
classDefinition.cartwheel = {'cartwheelLHandStart1Reps', 'cartwheelLHandStart1RepsMirrored'};


classDefinition.exercise = {...
                          'elbowToKnee1RepsLelbowStart',...
                          'elbowToKnee1RepsRelbowStart',...
                          'skier1RepsLstart',...
                          'squat1Reps',...
                             };
% classDefinition.kick = {'kickLFront1Reps', 'kickLFront1RepsMirrored',...
%                         'kickLSide1Reps', 'kickLSide1RepsMirrored',...
%                         'kickRFront1Reps', 'kickRFront1RepsMirrored',...
%                         'kickRSide1Reps', 'kickRSide1RepsMirrored'};



% classDefinition.punch = {'punchLFront1Reps', 'punchLSide1Reps', 'punchRFront1RepsMirrored', 'punchRSide1RepsMirrored',...
%                          'punchLFront1RepsMirrored', 'punchLSide1RepsMirrored', 'punchRFront1Reps', 'punchRSide1Reps'};



% classDefinition.rotateArms = {'rotateArmsBothBackward1Reps', ...
%                               'rotateArmsBothForward1Reps',...
%                               'rotateArmsLBackward1Reps',...
%                               'rotateArmsLForward1Reps',...
%                               'rotateArmsRBackward1RepsM',...
%                               'rotateArmsRForward1RepsM',...
%                               'rotateArmsLBackward1RepsM',...
%                               'rotateArmsLForward1RepsM',...
%                               'rotateArmsRBackward1Reps',...
%                               'rotateArmsRForward1Reps',...
%                               };






                   


% classDefinition.others = {...
% %                          'clap1Reps',...
% %                          'clapAboveHead1Reps',...
% %                          'hitRHandHead',...
%                           'elbowToKnee1RepsLelbowStart',...
%                           'elbowToKnee1RepsRelbowStart',...
%                           'skier1RepsLstart',...
%                           'squat1Reps',...
%                              };
                      % onPlace - Walk - movements not yet regarded.