close all;

global VARS_GLOBAL
%%%%%%%%%%%%%%%%% print skeleton trace poses
global VARS_GLOBAL_ANIM
if (isempty(who('VARS_GLOBAL_ANIM'))||isempty(VARS_GLOBAL_ANIM))
    VARS_GLOBAL_ANIM = emptyVarsGlobalAnimStruct;
end
VARS_GLOBAL_ANIM.ground_tile_size_factor = 1;
VARS_GLOBAL_ANIM.figure_color = [192 192 192]/255;
VARS_GLOBAL_ANIM.bounding_box_border_extension = 20;
VARS_GLOBAL_ANIM.figure_position = [5 150 320 240];
VARS_GLOBAL_ANIM.animated_skeleton_MarkerEdgeColor = 'red';%[200 200 200]/255;
VARS_GLOBAL_ANIM.animated_skeleton_MarkerFaceColor = 'red';%[200 200 200]/255;
VARS_GLOBAL_ANIM.animated_skeleton_MarkerSize = 20;
VARS_GLOBAL_ANIM.animated_skeleton_LineWidth = 4;
VARS_GLOBAL_ANIM.video_compression = 'PNG1';
rehash path;

downsampling_fac = 4;

VARS_GLOBAL_ANIM.figure_camera_file = ['cam_video_hits_elbowToKnee'];

load hits_elbowToKnee

hits = hits_DTW_postprocess(hits,DB_concat);
for k=1:length(hits)
    hits(k).frame_first_matched = hits(k).frame_first_matched*downsampling_fac-(downsampling_fac-1);
    hits(k).frame_last_matched = hits(k).frame_last_matched*downsampling_fac-(downsampling_fac-1);
end
%animateSimultaneous(hits,1,1,[],4,[4 0]);
%animateSimultaneous(hits,1,1,[],4,[4 0],'render/video_hits_elbowToKnee.avi',4,30);
%animateSimultaneous(hits,1,1,[],4,[4 0],'render/video_hits_elbowToKnee_slomo4.avi',1,30);

global VARS_GLOBAL_ANIM
if (isempty(who('VARS_GLOBAL_ANIM'))||isempty(VARS_GLOBAL_ANIM))
    VARS_GLOBAL_ANIM = emptyVarsGlobalAnimStruct;
end
VARS_GLOBAL_ANIM.video_compression = 'PNG1';

%replicateImage('render/emptyGray320x240.tif', 'render/video_hits_empty_prepad', 30, 1/30);
concatVideosSmooth_temporal(...
    {...
        'render/video_hits_empty_prepad',...
        'render/video_hits_elbowToKnee.avi',...
        'render/video_hits_elbowToKnee_slomo4.avi',...
        'render/video_hits_elbowToKnee_slomo4.avi',...
},...
    'render/video_hits_elbowToKnee_concat.avi',...
    {...
        [],...
        [],...
        [],...        
        [],...        
    },...
    [...
        NaN,...
        0.25,...
        0.25,...
        0.25,...
    ],...
    [...
        25 0;...
        0 0;...
        0 0;...
        0 5;...
    ]...
    );


