function s = emptyVarsGlobalAnimStruct
                   s = struct('animation_done',true,...
                              'range',[],...
                              'skel',[],...
                              'mot',[],...
                              'graphics_data',[],...      % struct array with handles to graphics data (planes, lines, etc.)
                              'graphics_data_index',0,... % index into graphics_data struct array, denoting the currently active figure
                              'frame_draw_time',0,...
                              'frames_drawn',0,...
                              'draw_labels',[],...        % boolean array the same size as skel and mot, indicating whether frame counter labels are to be drawn
                              'figure_position',[],...
                              'figure_color',[192 192 192]/255,...
                              'figure_camera_file',[],...
                              'ground_tile_size_factor',1,... % measures size of ground tiles in multiples of humerus lengths
                              'bounding_box_border_extension',1,... % how many tiles are to be appended around the ground plane?
                              'animated_skeleton_Color','black',...
                              'animated_skeleton_LineWidth',3,...
                              'animated_skeleton_LineStyle','-',...
                              'animated_skeleton_Marker','.',...
                              'animated_skeleton_MarkerSize',20,...
                              'animated_skeleton_MarkerEdgeColor','red',...
                              'animated_skeleton_MarkerFaceColor','red',...
                              'trace_pose_Color','yellow',...
                              'trace_pose_LineWidth',3,...
                              'trace_pose_LineStyle','-',...
                              'trace_pose_Marker','.',...
                              'trace_pose_MarkerSize',20,...
                              'trace_pose_MarkerEdgeColor',[200 200 200]/255,...
                              'trace_pose_MarkerFaceColor',[200 200 200]/255,...
                              'animated_point_MarkerSize',20,...
                              'animated_point_Marker','*',...
                              'animated_point_MarkerEdgeColor',[0 0 0],... % put RGB row vector here. MarkerFaceColor is user-determined... put empty value if MarkerEdgeColor==MarkerFaceColor is desired
                              'video_compression','HFYU',...
                              'video_flip_vert',false,...
                              'video_flip_horz',false);
%%%
% VARS_GLOBAL_ANIM.animated_skeleton_Marker = '.';
% VARS_GLOBAL_ANIM.animated_skeleton_MarkerSize = 30;
% VARS_GLOBAL_ANIM.animated_skeleton_MarkerFaceColor = [200 200 200]/255;
% VARS_GLOBAL_ANIM.animated_skeleton_MarkerEdgeColor = [200 200 200]/255;
% VARS_GLOBAL_ANIM.animated_point_MarkerSize = 25;
%                               'trace_pose_Color','black',...
%                               'trace_pose_LineWidth',2,...
%                               'trace_pose_LineStyle','-',...
%                               'trace_pose_Marker','o',...
%                               'trace_pose_MarkerSize',0.5,...
%                               'trace_pose_MarkerEdgeColor','black',...
%                               'trace_pose_MarkerFaceColor','black',...
  