function showTracePoses(skel,mot,frames)

global VARS_GLOBAL_ANIM

if (isempty(VARS_GLOBAL_ANIM)||isempty(VARS_GLOBAL_ANIM.graphics_data))
    VARS_GLOBAL_ANIM = emptyVarsGlobalAnimStruct;
    animate_initGraphics;
end

f = find(cell2mat({VARS_GLOBAL_ANIM.graphics_data.figure}) == gcf);
if (isempty(f))
    animate_initGraphics;
    f = gcf;
end

VARS_GLOBAL_ANIM.graphics_data_index = f;
for k=1:length(frames)
    VARS_GLOBAL_ANIM.graphics_data(f).trace_poses=...
        [VARS_GLOBAL_ANIM.graphics_data(f).trace_poses; ...
            createSkeletonLines({skel,mot},frames(k),...
                                                    VARS_GLOBAL_ANIM.trace_pose_Color,...
                                                    VARS_GLOBAL_ANIM.trace_pose_LineWidth,...
                                                    VARS_GLOBAL_ANIM.trace_pose_LineStyle,...
                                                    VARS_GLOBAL_ANIM.trace_pose_Marker,...
                                                    VARS_GLOBAL_ANIM.trace_pose_MarkerSize,...
                                                    VARS_GLOBAL_ANIM.trace_pose_MarkerEdgeColor,...
                                                    VARS_GLOBAL_ANIM.trace_pose_MarkerFaceColor)];
% {skel, mot}, frames, color, linewidth, linestyle, marker, markersize, markeredgecolor, markerfacecolor
end