function dT = deriveTimeline(T)

weights = [1 -8 0 8 -1];

dT     = zeros(size(T));

T = [   3*T(:,1)-2*T(:,2),...
        2*T(:,1)-T(:,2),...
          T,...
        2*T(:,end)-T(:,end-1),...
        3*T(:,end)-2*T(:,end-1)];

    
for frame = 3:size(T,2)-2
    dT(:,frame-2) = ...
              weights(1) * T(:,frame-2) ...
            + weights(2) * T(:,frame-1) ...
            + weights(3) * T(:,frame)   ...
            + weights(4) * T(:,frame+1) ...
            + weights(5) * T(:,frame+2);
end  
dT = dT / 12;
    
end