function index = index_struct
index = struct('files',cell(1,1),...
               'files_num',0,...
               'files_sampling_rate',[],...
               'files_frame_length',[],...
               'features_spec',[],...
               'features_num',0,...
               'segments',struct('features',[],'frames_start',[],'frames_length',[]),...
               'files_segment_length',[],...
               'lists',cell(1,1),...
               'lists_num',0,...
               'lists_length',[]);
