function jointTrajectories = C_forwardKinematicsQuat(skel,mot,varargin)

switch nargin
    case 2
        jointTrajectories = C_recursive_forwardKinematicsQuat(skel,...
                                                mot,...
                                                1,...
                                                mot.rootTranslation + repmat(skel.nodes(1).offset,1,mot.nframes),...
                                                C_quatmult(skel.rootRotationalOffsetQuat,mot.rotationQuat{1}),...
                                                mot.jointTrajectories);
    case 4
        sf=varargin{1};
        ef=varargin{2};
        
        jointTrajectories = mot.jointTrajectories;
        
        mot = cutMotion(mot,sf,ef);
        
        tmpTrajectories = C_recursive_forwardKinematicsQuat(skel,...
                                                mot,...
                                                1,...
                                                mot.rootTranslation + repmat(skel.nodes(1).offset,1,mot.nframes),...
                                                C_quatmult(skel.rootRotationalOffsetQuat,mot.rotationQuat{1}),...
                                                mot.jointTrajectories);
                                            
        for i=1:mot.njoints
           jointTrajectories{i,1}(:,sf:ef) = tmpTrajectories{i};  
        end
                                            
    otherwise
        error('Wrong num of Args!\n');
end