function plot_win_sort_variables(ud)

% PLOT_WIN_SORT_VARIABLES chooses a variable that underlies sorting.
% ---------------------------
% plot_win_sort_variables(ud)
% ---------------------------
% Description: chooses a variable that underlies sorting.
% Input:       {ud} userdata of parent window.

% © Liran Carmel
% Classification: Visualization
% Last revision date: 10-Jan-2005

% extract relevant parameters from {ud}
vsm = ud.data;
vars = ud.variables;
var_sort = ud.var_sort;

% open window
fig = figure('menubar','none','position',[300 300 250 350],...
    'numbertitle','off','name','Choose Variables to Sort Upon');

% define editable line
uicontrol(fig,'style','text','string','Variable #:',...
    'units','normalized','position',[0.05 0.9 0.22 0.05],...
    'background',[0.8 0.8 0.8],'horizontal','left');
% cmd = ['ud=get(gcf,''userdata'');' ...
%         'h_ed=ud.h_ed; h_lb=ud.h_lb; vars=ud.variables;' ...
%         'set(h_lb,''value'',find(vars==str2num(get(h_ed,''string''))));'];
h_ed = uicontrol(fig,'style','edit',...
    'units','normalized','position',[0.27 0.9 0.2 0.05],...
    'background',[0.8 0.8 0.8],'horizontal','left',...
    'callback','plot(vsmatrix,401)');

% define listbox
% cmd = ['ud=get(gcf,''userdata'');' ...
%         'h_ed=ud.h_ed; h_lb=ud.h_lb; vars=ud.variables;' ...
%         'set(h_ed,''string'',num2str(vars(get(h_lb,''value''))));'];
if length(vsm.variables) == 1
    h_lb = uicontrol(fig,'style','listbox',...
        'string',vsm.variables.name,...
        'units','normalized','position',[0.08 0.12 0.9 0.74],...
        'callback','plot(vsmatrix,402)');
else
    h_lb = uicontrol(fig,'style','listbox',...
        'string',vsm.variables(vars).name,...
        'units','normalized','position',[0.08 0.12 0.9 0.74],...
        'callback','plot(vsmatrix,402)');
end

% define OK and Cancel buttons
% cmd = ['this_fig = gcf; ud=get(gcf,''userdata'');' ...
%         'h_ed=ud.h_ed;' ...
%         'var_sort=str2num(get(h_ed,''string''));' ...
%         'main_fig=ud.main_fig;' ...
%         'ud=get(main_fig,''userdata''); vsm=ud.data;' ...
%         'if length(vsm.variables)==1,' ...
%         '[dummy idx] = sort(vsm.variables(:)); else,' ...
%         '[dummy idx] = sort(vsm.variables(var_sort,:)); end,' ...
%         'ud.var_sort=var_sort; ud.rearrangement = idx;' ...
%         'ud.grp_sort=[]; set(main_fig,''userdata'',ud);' ...
%         'plot(vsmatrix,1); close(this_fig)'];
uicontrol(fig,'style','push','string','O.K.',...
    'units','normalized','position',[0.125 0.02 0.3 0.07],...
    'callback','plot(vsmatrix,403)');
uicontrol(fig,'style','push','string','Cancel',...
    'units','normalized','position',[0.575 0.02 0.3 0.07],...
    'callback','close(gcf)');

% initialize window to previos selection
if ~isempty(var_sort)
    set(h_lb,'value',find(vars==var_sort));
    set(h_ed,'string',num2str(var_sort));
else
    set(h_lb,'value',1);
    set(h_ed,'string',num2str(vars(1)));
end

% define userdata
ud = struct('variables',vars,'var_sort',var_sort,'main_fig',ud.main_fig,...
    'h_ed',h_ed,'h_lb',h_lb);
set(gcf,'userdata',ud);