function scatter_win_select_variables(ud)

% SCATTER_WIN_SELECT_VARIABLES opens a window for selecting variables (scatter).
% --------------------------------
% scatter_win_select_variables(ud)
% --------------------------------
% Description: opens a window for selecting variables (scatter).
% Input:       {ud} userdata of parent window.

% © Liran Carmel
% Classification: Visualization
% Last revision date: 10-Jan-2005

% extract relevant parameters from {ud}
vsm = ud.data;
vars = ud.variables;

% open window
win_name = sprintf('Select Variables (total %d)',novariables(vsm));
fig = figure('menubar','none','position',[300 300 500 400],...
    'numbertitle','off','name',win_name);

% define editable text
uicontrol(fig,'style','text','horizontal','left',...
    'units','normalized','position',[0.05 0.88 0.2 0.05],...
    'string','Variable for x-axis:','background',[0.8 0.8 0.8]);
h_ed(1) = uicontrol(fig,'style','edit',...
    'units','normalized','position',[0.25 0.88 0.05 0.05],...
    'background',[0.8 0.8 0.8],'horizontal','left',...
    'callback','scatter(vsmatrix,101)');
uicontrol(fig,'style','text','horizontal','left',...
    'units','normalized','position',[0.55 0.88 0.2 0.05],...
    'string','Variable for y-axis:','background',[0.8 0.8 0.8]);
h_ed(2) = uicontrol(fig,'style','edit',...
    'units','normalized','position',[0.75 0.88 0.05 0.05],...
    'background',[0.8 0.8 0.8],'horizontal','left',...
    'callback','scatter(vsmatrix,102)');

% define listbox
h_lb(1) = uicontrol(fig,'style','listbox',...
    'string',name(vsm.variables),...
    'units','normalized','position',[0.05 0.12 0.4 0.75],...
    'callback','scatter(vsmatrix,103)');
h_lb(2) = uicontrol(fig,'style','listbox',...
    'string',name(vsm.variables),...
    'units','normalized','position',[0.55 0.12 0.4 0.75],...
    'callback','scatter(vsmatrix,104)');

% define OK and Cancel buttons
uicontrol(fig,'style','push','string','O.K.',...
    'units','normalized','position',[0.125 0.03 0.3 0.06],...
    'callback','scatter(vsmatrix,105)');
uicontrol(fig,'style','push','string','Cancel',...
    'units','normalized','position',[0.575 0.03 0.3 0.06],...
    'callback','close(gcf)');

% initialize window to previos selection
set(h_lb(1),'value',vars(1));
set(h_ed(1),'string',num2str(vars(1)));
set(h_lb(2),'value',vars(2));
set(h_ed(2),'string',num2str(vars(2)));
 
% define userdata
ud = struct('data',vsm,'variables',vars,'h_ed',h_ed,'h_lb',h_lb,...
    'main_fig',ud.main_fig);
set(gcf,'userdata',ud);