% concatVideosSmooth_temporal({...
% 	'01_title_submission_version.avi',...
% 	'02_introduction_1.avi',...
% 	'03_introduction_2.avi',...
% 	'04_similarity.avi',...
% 	'05_walk_video_final.avi',...
% 	'06_feature_walk_plane_video.avi',...
% 	'07_feature_boxing_video.avi',...
% 	'08_features_touch_angle_video_final.avi',...
% 	'09_walk_adaptive_segmentation_video1_slomo_title.avi',...
% 	'10_walk_adaptive_segmentation_video2_combined_final.avi',...
% 	'11_walk_adaptive_segmentation_video3_combined_final.avi',...
% 	'12_walk_query_and_exact_hits.avi',...
% 	'13_overlay_query_features10.avi',...
% 	'14_walk_fuzzy_query_hit_video.avi',...
%     '15_table_indexing.avi',...
%     '16_retrieval_final.avi',...
% 	'17_acknowledgements.avi'},...
% 	'Efficient_CBR_of_MoCap_Data.avi',{...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	[],...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	[],...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif',...
% 	'emptyGray512x384_special.tif'},...
% 	0.25);

concatVideosSmooth_temporal({...
	'01_title_submission_version.avi',...
	'02_introduction_1.avi',...
	'03_introduction_2.avi',...
	'04_similarity.avi',...
	'05_walk_video_final.avi',...
	'06_feature_walk_plane_video.avi',...
	'07_feature_boxing_video.avi',...
	'08_features_touch_angle_video_final.avi',...
	'09_walk_adaptive_segmentation_video1_slomo_title.avi',...
	'10_walk_adaptive_segmentation_video2_combined_final.avi',...
	'11_walk_adaptive_segmentation_video3_combined_final.avi',...
	'12_walk_query_and_exact_hits.avi',...
	'13_overlay_query_features10.avi',...
	'14_walk_fuzzy_query_hit_video.avi',...
    '15_table_indexing.avi',...
    '16_retrieval_final.avi',...
	'17_acknowledgements.avi'},...
	's:\roedert\matlab\mocap\videos\final\Efficient_CBR_of_MoCap_Data.avi',{...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	[],...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	[],...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif',...
	'emptyGray512x384.tif'},...
	0.25);