function P=newOptProbs(varargin)

switch nargin
    case 0
        joints=[5 8 17 21 28];
    case 1
        joints=varargin{1};
    otherwise
        error('newOptProbs: Wrong number of args!\n');
end

if(size(joints,2)>3)

    P=struct(   'Display','iter', ...
                'startValue',[], ...
                'Iterations',1000, ...
                'FuncEvals',5000, ...
                'TolFun' , 0.01, ...
                'TolFunX', 0.01, ...
                'x',[], ...
                'x_1',[], ...
                'x_2',[], ...
                'joints',joints, ...
                'recmot',[]);
else
    P=struct(   'Display','iter', ...
                'startValue',[], ...
                'Iterations',1000, ...
                'FuncEvals',5000, ...
                'TolFun' , 0.1, ...
                'TolFunX', 0.1, ...
                'x',[], ...
                'x_1',[], ...
                'x_2',[], ...
                'joints',joints, ...
                'recmot',[]);
end