function [localRotations] = getLocalSystems(skel,mot)
[localRotations] = recursive_getLocalSystems(skel,...
                    mot,...
                    1,...
                    quatmult(repmat(skel.rootRotationalOffsetQuat,1,mot.nframes),mot.rotationQuat{1}),...
                    mot.rotationQuat);