

% db_hdm_cmu.pos          = [db_hdm.pos db_cmu.pos];
% db_hdm_cmu.quat         = [db_hdm.quat db_cmu.quat];
% db_hdm_cmu.motNames     = [db_hdm.motNames;db_cmu.motNames];
% db_hdm_cmu.motStartIDs  = [db_hdm.motStartIDs;db_cmu.motStartIDs+size(db_hdm.pos,2)];

allFiles = {'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_01.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_02.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_03.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_04.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_05.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_06.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_07.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_08.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_09.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_10.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_11.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_12.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_13.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_14.amc';...
            'E:\CMU_2008-12-18\all_asfamc\subjects\86\86_15.amc';...
            '/mnt/breithorn/shareII/MoCap-Daten/HDM_DB/HDM05/HDM05_amc/bk/HDM_bk_01-01_01_120.amc';...
            '/mnt/breithorn/shareII/MoCap-Daten/HDM_DB/HDM05/HDM05_amc/bk/HDM_bk_02-01_01_120.amc';...
            '/mnt/breithorn/shareII/MoCap-Daten/HDM_DB/HDM05/HDM05_amc/bk/HDM_bk_03-05_01_120.amc';...
            '/mnt/breithorn/shareII/MoCap-Daten/HDM_DB/HDM05/HDM05_amc/bk/HDM_bk_04-01_01_120.amc';...
            };

allFiles2 = {'86_01.amc';'86_02.amc';...
            '86_03.amc';...
            '86_04.amc';...
            '86_05.amc';...
            '86_06.amc';...
            '86_07.amc';...
            '86_08.amc';...
            '86_09.amc';...
            '86_10.amc';...
            '86_11.amc';...
            '86_12.amc';...
            '86_13.amc';...
            '86_14.amc';...
            '86_15.amc';...
            'HDM_bk_01-01_01_120.amc';...
            'HDM_bk_02-01_01_120.amc';...
            'HDM_bk_03-05_01_120.amc';...
            'HDM_bk_04-01_01_120.amc';...
            };

resultMatrix        = cell(length(allFiles),4);
resultMatrixNums    = zeros(length(allFiles),9);

for i=16:19
    
    fprintf('%i / %i\n',i,length(allFiles));
    
    filename = allFiles{i};

    load([filename '.mat'], 'skel', 'mot');
    
    mot = changeFrameRate(skel,mot,30);
    
    resultMatrixNums(i,end) = mot.nframes;


    % HDM\m ---------------------------------------------------------------
    index = 1;
    resultMatrix{i,index}           = recMotKD_acc3(skel,mot,deleteMotFromDB(db_hdm,allFiles2{i}));
    resultMatrix{i,index}.db        = 'hdm';   
    resultMatrixNums(i,index*2-1)   = resultMatrix{i,index}.dists.pointcloud_cm;
    resultMatrixNums(i,index*2)     = max(resultMatrix{i,index}.dists.pointCloud_perFrame);
    % CMU\{m} -------------------------------------------------------------
%     index = 2;
%     resultMatrix{i,index}           = recMotKD_acc3(skel,mot,db_cmuTrunc);
%     resultMatrix{i,index}.db        = 'cmu_trunc';
%     resultMatrixNums(i,index*2-1)   = resultMatrix{i,index}.dists.pointcloud_cm;
%     resultMatrixNums(i,index*2)     = max(resultMatrix{i,index}.dists.pointCloud_perFrame);
    % CMU\m ---------------------------------------------------------------
%     index = 3;
%     resultMatrix{i,index}           = recMotKD_acc3(skel,mot,deleteMotFromDB(db_cmu,allFiles2{i}));
%     resultMatrix{i,index}.db        = 'cmu';
%     resultMatrixNums(i,index*2-1)   = resultMatrix{i,index}.dists.pointcloud_cm;
%     resultMatrixNums(i,index*2)     = max(resultMatrix{i,index}.dists.pointCloud_perFrame);
%     % HDMuCMU\m
%     index = 4;
%     resultMatrix{i,index}           = recMotKD_acc3(skel,mot,deleteMotFromDB(db_hdm_cmu,allFiles2{i}));
%     resultMatrix{i,index}.db        = 'hdm_cmu';
%     resultMatrixNums(i,index*2-1)   = resultMatrix{i,index}.dists.pointcloud_cm;
%     resultMatrixNums(i,index*2)     = max(resultMatrix{i,index}.dists.pointCloud_perFrame);
    
    save recsNew resultMatrix resultMatrixNums;
end
    
    
    