function sensor = sensor3d(varargin)
%3DSENSOR Summary of this function goes here
%   Detailed explanation goes here
drawAxis = true;

if(nargin == 1)
    scale = varargin{1};
else
    scale = 1.0;
end
% [width, length, height] in millimeter
w = 38 * scale;
l = 53 * scale;
h = 21 * scale;
if(drawAxis)
    sens = [...
        .0 .0 .0;...
        l .0 .0;...
        l .0 h;...
        .0 .0 h;...
        .0 w .0;...
        l w .0;...
        l w h;...
        .0 w h;...
        ];
    cube = [...
        .0 .0 .0;...
        h .0 .0;...
        h .0 h;...
        .0 .0 h;...
        .0 h .0;...
        h h .0;...
        h h h;...
        .0 h h;...
        ];
    xAxis = cube/2;
    yAxis = xAxis;
    zAxis = xAxis;
    xAxis(:,1) = xAxis(:,1)*2+l;
    yAxis(:,2) = yAxis(:,2)*2+w;
    zAxis(:,3) = zAxis(:,3)*2+h;
    verts = [sens;xAxis;yAxis;zAxis];
    verts = [verts(:,1)-l/2 verts(:,2)-w/2 verts(:,3)-h/2];
    f = [...
        1,2,3,4;...
        2,6,7,3;...
        6,5,8,7;...
        5,1,4,8;...
        4,3,7,8;...
        1,2,6,5;...
        ];
    faces = [f; f+8; f+16; f+24];
    CData = [...
        .0 .75 .0;...
        .0 .0 .75;...
        .0 .75 .0;...
        .0 .0 .75;...
        .75 .0 .0;...
        .75 .0 .0;...
        ];
    CData = [CData;...
        repmat([.0 .0 .75],6,1);...
        repmat([.0 .75 .0],6,1);...
        repmat([.75 .0 .0],6,1);];
else
    verts = [...
        -l,-w,-h;...
        l,-w,-h;...
        l,-w,h;...
        -l,-w,h;...
        -l,w,-h;...
        l,w,-h;...
        l,w,h;...
        -l,w,h;...
        ];
    verts = verts/2.0;
    
    faces = [...
        1,2,3,4;...
        2,6,7,3;...
        6,5,8,7;...
        5,1,4,8;...
        4,3,7,8;...
        1,2,6,5;...
        ];
    CData = [...
        .0 .75 .0;...
        .0 .0 .75;...
        .0 .75 .0;...
        .0 .0 .75;...
        .75 .0 .0;...
        .75 .0 .0;...
        ];
end
sensor = struct(...
    'vertices',verts,...
    'faces',faces,...
    'faceVertexCData',CData,...
    'faceColor','flat');
end

