function obj = emptyObject(varargin)
%% using inputParser function to handle variable inputs
p = inputParser;
p.addOptional('id', [], @(x) isempty(x));
p.addOptional('name', '', @ischar);
p.addOptional('type', 'object', @ischar);
p.addOptional('size', 1, @isnumeric);
p.addOptional('animated',false, @(x) isempty(x));
p.addOptional('nFrames',[], @(x) x>=1);
p.addOptional('labeled',false, @(x) islogical(x));
p.addOptional('labelText','',@(x) ischar(x));
p.addOptional('vertices',[], @(x) size(x,2) == 3);
p.addOptional('faces',[], @(x) size(x,2) == 3 || size(x,2) == 4);
p.addOptional('boundingBox',[], @(x) size(x,1) == 6 && size(x,2) == 1);    % [xmin;xmax;ymin;ymax;zmin;zmax;]
p.addOptional('faceColor',[0.8 0.0 0.0], @(x) isColor(x));
p.addOptional('faceVertexCData',[]);    % color information for each vertex faceColor has to be 'flat'
p.addOptional('faceAlpha',1.0, @(x) x>=0.0 && x<=1.0);
p.addOptional('edgeColor',[0.0 0.0 0.0], @(x) isColor(x)); % 'edgeColorStream',[],...
p.addOptional('faceAlphaStream',[]);
p.addOptional('faceColorStream',[]);
p.addOptional('verticesStream',[], @(x) isempty(x));
p.addOptional('labelStream',[]);
p.addOptional('position',[]);
p.addOptional('orientation',[]);
p.addOptional('labelHandle',[], @(x) isempty(x));
p.addOptional('objectHandle',[], @(x) isempty(x));
p.parse(varargin{:});
obj = p.Results;

%% old empty object without use of inputparser
% obj = struct(...
%     'id',[],...
%     'name','',...
%     'type','',...
%     'size',1,...
%     'animated',false,...
%     'nFrames',[],...
%     'labeled',false,...
%     'labelText','',...
%     'vertices',[],...
%     'faces',[],...
%     'boundingBox',[],...    % [xmin;xmax;ymin;ymax;zmin;zmax;]
%     'faceColor',[],...
%     'faceVertexCData',[],...    % color information for each vertex faceColor has to be 'flat'
%     'faceAlpha',1.0,...
%     'edgeColor',[0.0 0.0 0.0],...      % 'edgeColorStream',[],...
%     'faceAlphaStream',[],...
%     'faceColorStream',[],...
%     'verticesStream',[],...
%     'labelStream',[],...
%     'position',[],...
%     'orientation',[],...
%     'labelHandle',[],...
%     'objectHandle',[]);
end