function scene = emptyScene
%EMPTYSCENE Summary of this function goes here
%   Detailed explanation goes here

emptyBone = struct(...
    'id',[],...
    'parentID',[],...
    'name','',...
    'type','',...
    'vertices',[],...
    'vertstream',[],...
    'faces',[],...
    'facecolor',[],...
    'labelHandle',[],...
    'labelStream',[],...
    'objectHandle',[],...
    'headPos',[],...
    'tailPos',[]);

emptyArmature = struct(...
    'alphaStream',...
    'colorStream',...
    'skel',[],...
    'mot',[],...
    'numBones',0,...
    'color',[],...
    'bones',emptyBone,...
    'rendered',false);

emptyMarker = struct(...
    'faceAlphaStream',[],...
    'colorStream',[],...
    'type','',...
    'nframes',[],...
    'vertices',[],...
    'vertstream',[],...
    'faces',[],...
    'facecolor',[],...
    'edgecolor',[],...
    'labelHandle',[],...
    'labelStream',[],...
    'objectHandle',[]);

status = struct(...
    'curFrame',[],...
    'frameTime',[],...
    'speed',1.0,...
    'lastRenderTime',0.0333,...      % 1 sec / 30 frames
    'delay',.0,...
    'curFps',.0,...
    'reverse',false,...
    'looped',false,...
    'sliderHandle',[],...
    'curFpsLabel',[],...
    'curFrameLabel',[],...
    'curSkel',[],...
    'animationTime',[],...
    'nframes',0,...
    'boundingBox',[],...
    'samplingRate',120,...
    'numMarkerHandle',[],...
    'numArmatures',0,...
    'numMarkers',0,...
    'drawLabels',false,...
    'running',false);

scene = struct(...
    'fig',[],...
    'options',[],...
    'numObjects',0,...
    'status',status,...
    'sceneIsEmpty',true,...
    'animatedObjects',[],...
    'solidObjects',[],...
    'objects',emptyObject,...           % list of objects beside the armatures
    'armatures',emptyArmature);         % list of armatures
end
