function defaultOptions = getDefaultOptions(varargin)
%% using inputParser function to handle variable inputs
p = inputParser;
p.addOptional('resolution', 1.0, @(x)x>=1.0 && x<=3.0);
p.addOptional('groundPlane', true, @(x)x == 1 || x == 0);
p.addOptional('groundPlaneColor', [0.7 0.7 0.7;1.0 1.0 1.0],...
    @(x) isColor(x(1,:)) && isColor(x(2,:)) && ...
    size(x,1) == 2 && size(x,2) == 3);
p.addOptional('groundPlaneTileSize', 20.0, @(x) x>0.0);
p.addOptional('groundPlaneAlpha', 1.0, @(x) x>=0.0 && x<=1.0);
p.addOptional('skelEdgeColor', [.0 .0 .0], @(x) isColor(x));
p.addOptional('markerEdgeColor', [.0 .0 .0], @(x) isColor(x));
p.addOptional('ambientStrength', 1.0, @(x) x>=0.0 && x<=1.0);
p.addOptional('diffuseStrength', 1.0, @(x) x>=0.0 && x<=1.0);
p.addOptional('specularStrength', 1.0, @(x) x>=0.0 && x<=1.0);
p.addOptional('light', true, @(x)x == 1 || x == 0);
p.addOptional('mainAxis','y', @(x) max(ismember(['x';'y';'z'],x)) > 0 && ...
    size(x,1) == 1 && size(x,2) == 1);
p.addOptional('doTheMonkey',struct('size',0,'orientation',[1.0 0.0 0.0 0.0]') ...
    );                          %scalar for size of the monkey-head 
                                %doTheMonkey == 0 -> default sphere, 
                                %doTheMonkey > 0 -> monkey head (value
                                %should be 2.5 to 5);
p.parse(varargin{:});
defaultOptions = p.Results;

%% old options struct without use of inputparser
% defaultOptions = struct(...
%     'resolution',1.0,...        % resolution of sphere objects [1.0,3.0]
%     'groundPlane',true,...      % draw groundplane [true/false]
%     'groundPlaneColor',[.7 .7 .7;...    %color1 and color2 of tiles [2x3]
%     1 1 1],...
%     'groundPlaneTileSize',20,...
% 	'groundPlaneAlpha',1,...
%     'skelEdgeColor',[.0 .0 .0],...
%     'markerEdgeColor',[.0 .0 .0],...
%     'ambientStrength',1.0,...
%     'diffuseStrength',1.0,...
%     'specularStrength',1.0,...
%     'light',false,...
%     'mainAxis','y',...
%     'doTheMonkey',struct('size',0,'orientation',[1.0 0.0 0.0 0.0]') ...
%     );                          %scalar for size of the monkey-head 
%                                 %doTheMonkey == 0 -> default sphere, 
%                                 %doTheMonkey > 0 -> monkey head (value
%                                 %should be 2.5 to 5
end