function l = getLight(varargin)
if(nargin == 0)
    l = struct(...
        'color',[1 1 1],...
        'position',[0.0 0.0 0.0],...
        'style','local'...
        );
elseif(nargin == 2)
    l = struct(...
        'color',varargin{1},...
        'position',varargin{2},...
        'style','local'...
        );
elseif(nargin == 3)
    l = struct(...
        'color',varargin{1},...
        'position',varargin{2},...
        'style',varargin{3}...
        );
end
end