function renderScene()
%RENDERSCENE Summary of this function goes here
%   Detailed explanation goes here
global SCENE
if(SCENE.numObjects >0)
    for obj = SCENE.objects
        if(strcmp(obj.type,'label'))
            pos = obj.position;
            labelObj = text(pos(1),pos(2),pos(3),obj.labelText,...
                'Visible','on',...
                'FontWeight','bold',...
                'Color',obj.faceColor);
        else
            renderObj = patch(...
                'Vertices',obj.vertices,...
                'AmbientStrength',SCENE.options.ambientStrength,...
                'DiffuseStrength',SCENE.options.diffuseStrength,...
                'SpecularStrength',SCENE.options.specularStrength,...
                'Faces',obj.faces,...
                'FaceVertexCData',obj.faceVertexCData,...
                'EdgeColor',obj.edgeColor,...
                'FaceAlpha',obj.faceAlpha,...
                'FaceColor',obj.faceColor);
            SCENE.objects(obj.id).objectHandle = renderObj;
        end
    end
end
end