function renderMarkers( )
global SCENE
markers = SCENE.markers;
numMarkers = size(markers,2);
for i = 1:numMarkers
    renderObj = patch(...
        'facealpha',SCENE.markers(i).faceAlphaStream(1),...
        'AmbientStrength',SCENE.options.ambientStrength,...
        'DiffuseStrength',SCENE.options.diffuseStrength,...
        'SpecularStrength',SCENE.options.specularStrength,...
        'vertices',SCENE.markers(i).vertices,...
        'faces',SCENE.markers(i).faces,...
        'edgecolor',SCENE.markers(i).edgecolor,...
        'facecolor',SCENE.markers(i).colorStream(1,:));
    SCENE.markers(i).objectHandle = renderObj;
end
end