function verticesOut = translateVertices( vertices, offset )
%TRANSLATEVERTICES Summary of this function goes here
%   Detailed explanation goes here
verticesOut = [...
    vertices(:,1)+offset(1)...
    vertices(:,2)+offset(2)...
    vertices(:,3)+offset(3)];
end