function jointPositions = fK_Quat_frame(rotationQuat, rootTranslation, nodes, rootRotationalOffsetQuat)

jointPositions = recursive_fK_Quat_frame(1,...
                                                 rotationQuat, ...
                                                 nodes, ...
                                                 rootTranslation + nodes(1).offset,...
                                                 quatmult( rootRotationalOffsetQuat, rotationQuat{1} ),...
                                                 [], ...
                                                 []);